services:
    ankerctl:
        image: django01982/ankerctl:local
        build: .
        container_name: ankerctl
        restart: unless-stopped

        # host-mode networking is required for pppp communication with the
        # printer, since it is an asymmetrical udp protocol.
        network_mode: host

        # Load environment variables from .env file.
        # Copy .env.example to .env and adjust values as needed.
        env_file:
            - .env

        volumes:
            - ankerctl_vol:/home/ankerctl/.config/ankerctl
            - captures_vol:/captures
            - logs_vol:/logs

volumes:
    ankerctl_vol:
    captures_vol:
    logs_vol:


